/*
* Copyright 2025 heipiao233

* This file is part of "FH-UI for Slint".
* "FH-UI for Slint" is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
* "FH-UI for Slint" is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Foobar. If not, see <https://www.gnu.org/licenses/>. 
*/
import { FHPalette, FHColor, FHFontSettings, FHSizeSettings } from "styling.slint";
import { FHInteract } from "interactive.slint";
export component CheckBox {
    in property <string> text;
    in property <bool> enabled <=> i-touch-area.enabled;
    out property <bool> has-focus: i-focus-scope.has-focus;
    in-out property <bool> checked;

    callback toggled;

    in property <FHColor> color: FHPalette.general; // FH specific
    accessible-enabled: root.enabled;
    accessible-checkable: true;
    accessible-label: root.text;
    accessible-checked <=> root.checked;
    accessible-role: checkbox;
    height: interact.height;
    accessible-action-default => {
        root.checked = !root.checked;
        root.toggled();
    }

    forward-focus: i-focus-scope;

    HorizontalLayout {
        spacing: 10px;
        visible: true;
        interact := FHInteract {
            hovered: i-touch-area.has-hover;
            focused: i-focus-scope.has-focus;
            enabled: root.enabled;
            has-background: checked;
            has-border: true;
            has-corner: checked;
            color: root.color;
    
            width: self.height;
            height: FHSizeSettings.icon-size-small;
            pressing <=> i-touch-area.pressed;
        }
    
        txt := Text {
            text: text;
            vertical-alignment: center;
            color: interact.foreground-outer;
            font-size: FHFontSettings.body.font-size;
            font-weight: FHFontSettings.body.font-weight;
        }
    }

    i-touch-area := TouchArea {
        clicked => {
            if (root.enabled) {
                root.checked = !root.checked;
                root.toggled();
            }
        }
    }

    i-focus-scope := FocusScope {
        x: 0;
        width: 0;
        enabled <=> root.enabled;

        key-pressed(event) => {
            if (event.text == " " || event.text == "\n") {
                i-touch-area.clicked();
                 return accept;
            }

            return reject;
        }
    }

}