// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { FHFontSettings, FHPalette } from "styling.slint";

export component GroupBox {
    in property <string> title <=> label.text;
    in property <bool> enabled: true;

    accessible-role: groupbox;
    accessible-label: root.title;
    accessible-enabled: root.enabled;

    VerticalLayout {
        spacing: 8px;
        padding-top: 16px;
        padding-bottom: 8px;
        alignment: start;

        label := Text {
            text: "aaa";
            vertical-stretch: 0;
            color: !root.enabled ? FHPalette.disabled-foreground : FHPalette.foreground;
            font-size: FHFontSettings.body-strong.font-size;
            font-weight: FHFontSettings.body-strong.font-weight;
        }

        Rectangle {
            background: FHPalette.border;
            height: 1px;
        }

        GridLayout {
            padding: 8px;
            @children
        }
    }
}
