/*
* Copyright 2025 heipiao233

* This file is part of "FH-UI for Slint".
* "FH-UI for Slint" is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
* "FH-UI for Slint" is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Foobar. If not, see <https://www.gnu.org/licenses/>. 
*/
import { FHFontSettings, FHPalette } from "styling.slint";

export component GroupBox {
    in property <string> title <=> label.text;
    in property <bool> enabled: true;

    accessible-role: groupbox;
    accessible-label: root.title;
    accessible-enabled: root.enabled;

    VerticalLayout {
        spacing: 8px;
        padding-top: 16px;
        padding-bottom: 8px;
        alignment: start;

        label := Text {
            text: "aaa";
            vertical-stretch: 0;
            color: !root.enabled ? FHPalette.disabled-foreground : FHPalette.foreground;
            font-size: FHFontSettings.body-strong.font-size;
            font-weight: FHFontSettings.body-strong.font-weight;
        }

        Rectangle {
            background: FHPalette.border;
            height: 1px;
        }

        GridLayout {
            padding: 8px;
            @children
        }
    }
}
