// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: GPL-3.0-only OR LicenseRef-Slint-Royalty-free-2.0 OR LicenseRef-Slint-Software-3.0

import { FHPalette } from "styling.slint";

export component ProgressIndicator {
    in property <float> progress: 0.1;
    in property <bool> indeterminate: true;

    min-height: 10px;
    horizontal-stretch: 1;
    vertical-stretch: 0;
    accessible-role: progress-indicator;
    accessible-value: !root.indeterminate ? root.progress : "";
    accessible-value-minimum: 0.0;
    accessible-value-maximum: 1.0;

    Rectangle {
        clip: true;
        background: FHPalette.alternate-background;

        track := Rectangle {
            width: !root.indeterminate ?  parent.width * min(1, max(0, root.progress)) : parent.width;
            height: 100%;
            x: !root.indeterminate ? 0px : -parent.width + (parent.width * mod(animation-tick(), 2s) / 1s);
            background: FHPalette.general.dark;
        }
    }
}
