export { Button } from "button.slint";
export { ScrollView } from "scrollview.slint";
export { ListItem } from "components.slint";
export { LineEdit } from "lineedit.slint";
/*
* Copyright 2025 heipiao233

* This file is part of "FH-UI for Slint".
* "FH-UI for Slint" is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
* "FH-UI for Slint" is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Foobar. If not, see <https://www.gnu.org/licenses/>. 
*/
import { FHPalette } from "styling.slint";

export global StyleMetrics {
    out property <length> layout-spacing: 10px;
    out property <length> layout-padding: 12px;
    out property <length> text-cursor-width: 1px;
    out property <color> window-background: FHPalette.background;
    out property <color> default-text-color: FHPalette.foreground;
    out property <color> textedit-background: FHPalette.alternate-background;
    out property <color> textedit-text-color: FHPalette.foreground;
    out property <color> textedit-background-disabled: FHPalette.alternate-background;
    out property <color> textedit-text-color-disabled: FHPalette.foreground;
    out property <bool> dark-color-scheme: Palette.color-scheme == ColorScheme.dark;
}

export global Palette {
    out property <brush> background: FHPalette.background;
    out property <brush> foreground: FHPalette.foreground;
    out property <brush> alternate-background: FHPalette.alternate-background;
    out property <brush> alternate-foreground: FHPalette.foreground;
    out property <brush> control-background: FHPalette.general.dark;
    out property <brush> control-foreground: white;
    out property <brush> accent-background: FHPalette.general.dark;
    out property <brush> accent-foreground: white;
    out property <brush> selection-background: FHPalette.selection-background;
    out property <brush> selection-foreground: FHPalette.selection-foreground;
    out property <brush> border: FHPalette.border;
    in-out property <ColorScheme> color-scheme <=> FHPalette.color-scheme;
}
