/*
* Copyright 2025 heipiao233

* This file is part of "FH-UI for Slint".
* "FH-UI for Slint" is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
* "FH-UI for Slint" is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Foobar. If not, see <https://www.gnu.org/licenses/>. 
*/
import { Button } from "button.slint";
import { Icons, FHSizeSettings } from "styling.slint";

export component Switch {
    in property <bool> enabled: true;
    in property <string> text;
    in-out property <bool> checked;
    out property <bool> has-focus: btn.has-focus;

    callback toggled;
    vertical-stretch: 0;
    horizontal-stretch: 0;
    accessible-enabled: root.enabled;
    accessible-label: root.text;
    accessible-checkable: true;
    accessible-checked <=> root.checked;
    accessible-role: switch;
    accessible-action-default => {
        root.checked = !root.checked;
        root.toggled();
    }
    forward-focus: btn;
    height: FHSizeSettings.component-height;

    btn := Button {
        enabled: root.enabled;
        text: root.text;
        checkable: true;
        checked <=> root.checked;
        height: root.height;
        width: root.width;
        icon: checked ? Icons.switch-on : Icons.switch-off;
        colorize-icon: true;
        clicked => {
            toggled();
        }
    }
}