/*
* Copyright 2025 heipiao233

* This file is part of "FH-UI for Slint".
* "FH-UI for Slint" is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
* "FH-UI for Slint" is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
* You should have received a copy of the GNU General Public License along with Foobar. If not, see <https://www.gnu.org/licenses/>. 
*/
import { FHPalette, FHFontSettings, Icons } from "styling.slint";
import { ListView } from "builtin:/common/listview.slint";
import { FHInteract } from "interactive.slint";

component TableViewColumn inherits Rectangle {
    in property <SortOrder> sort-order: SortOrder.unsorted;
    out property <brush> foreground: interact.foreground;

    callback clicked <=> touch-area.clicked;
    callback adjust_size(length);

    min-height: max(24px, layout.min-height);
    // background: FHPalette.general.dark;

    touch-area := TouchArea {
        width: parent.width - 11px;
    }

    // border
    Rectangle {
        y: parent.height - self.height;
        width: 100%;
        height: 1px;
        background: FHPalette.border;
    }

    interact := FHInteract {
        width: 100%;
        height: 100%;
        hovered: touch-area.has-hover;
        pressing: touch-area.pressed;
        has-background: true;
        has-border: false;
        enabled: true;
        layout := HorizontalLayout {
            padding-left: 8px;
            padding-right: 8px;
            spacing: 2px;
    
            HorizontalLayout {
                @children
            }
    
            icon := Image {
                image-fit: contain;
                colorize: foreground;
                visible: root.sort-order != SortOrder.unsorted;
                width: 12px;
                y: (parent.height - self.height) / 2;
                source: root.sort-order == SortOrder.ascending ? Icons.up : Icons.down;
    
                animate colorize { duration: 150ms; }
            }
        }
    }

    Rectangle {
        x: parent.width - 1px;
        width: 1px;
        background: FHPalette.border;

        movable-touch-area := TouchArea {
            width: 10px;
            mouse-cursor: ew-resize;

            moved => {
                if (self.pressed) {
                    adjust_size(self.mouse-x - self.pressed-x);
                }
            }
        }
    }
}

component TableViewCell inherits Rectangle {
    clip: true;

    HorizontalLayout {
        padding: 8px;

        @children
    }
}

component TableViewRow inherits Rectangle {
    in property <bool> selected;
    in property <bool> even;

    callback clicked <=> touch-area.clicked;
    callback pointer-event(event: PointerEvent, position: Point);


    min-width: layout.min-width;
    min-height: max(24px, layout.min-height);
    background: root.even ? FHPalette.general.glass-bg : FHPalette.background;

    interact := FHInteract {
        height: parent.height;
        width: parent.width;
        pressing: touch-area.pressed;
        hovered: touch-area.has-hover;
        focused: root.selected;
        has-background: root.selected;
        has-corner: false;
        has-border: false;

        layout := HorizontalLayout {
           @children
        }
    }

    touch-area := TouchArea {
        pointer-event(pe) => {
            root.pointer-event(pe, {
                x: self.absolute-position.x + self.mouse-x,
                y: self.absolute-position.y + self.mouse-y,
            });
        }
    }
}

export component StandardTableView {
    in property <[[StandardListViewItem]]> rows;
    out property <int> current-sort-column: -1;
    in-out property <[TableColumn]> columns;
    in-out property <int> current-row: -1;

    callback sort-ascending(column: int);
    callback sort-descending(column: int);
    callback row-pointer-event(row: int, event: PointerEvent, position: Point);
    callback current-row-changed(current-row: int);

    public function set-current-row(index: int) {
        if (index < 0 || index >= rows.length) {
            return;
        }

        current-row = index;
        current-row-changed(current-row);

        if (current-item-y < 0) {
            scroll-view.viewport-y += 0 - current-item-y;
        }

        if (current-item-y + item-height > scroll-view.visible-height) {
            scroll-view.viewport-y -= current-item-y + item-height - scroll-view.visible-height;
        }
    }

    private property <length> min-header-height: 32px;
    private property <length> item-height: scroll-view.viewport-height / rows.length;
    private property <length> current-item-y: scroll-view.viewport-y + current-row * item-height;

    function sort(index: int) {
        if (root.current-sort-column != index) {
            root.columns[root.current-sort-column].sort-order = SortOrder.unsorted;
        }

        if(root.columns[index].sort-order == SortOrder.ascending) {
            root.columns[index].sort-order = SortOrder.descending;
            root.sort-descending(index);
        } else {
            root.columns[index].sort-order = SortOrder.ascending;
            root.sort-ascending(index);
        }

        root.current-sort-column = index;
    }

    min-width: 400px;
    min-height: 200px;
    horizontal-stretch: 1;
    vertical-stretch: 1;
    forward-focus: focus-scope;
    accessible-role: table;

    VerticalLayout {
        Rectangle {
            clip: true;
            vertical-stretch: 0;
            min-height: root.min-header-height;
            background: FHPalette.background;

            header-layout := HorizontalLayout {
                width: max(self.preferred-width, parent.width);
                x: scroll-view.viewport-x;
                padding-right: 6px;
                min-height: root.min-header-height;

                for column[index] in root.columns : TableViewColumn {
                    sort-order: column.sort-order;
                    horizontal-stretch: column.horizontal-stretch;
                    min-width: max(column.min-width, column.width);
                    preferred-width: self.min-width;
                    max-width: (index < columns.length && column.width >= 1px) ? max(column.min-width, column.width) : 100000px;

                    clicked => {
                        root.sort(index);
                    }

                    adjust-size(diff) => {
                        column.width = max(1px, self.width + diff);
                    }

                    Text {
                        vertical-alignment: center;
                        text: column.title;
                        font-weight: FHFontSettings.body.font-weight;
                        font-size: FHFontSettings.body.font-size;
                        color: parent.foreground;
                        overflow: elide;
                    }
                }
            }
        }

        scroll-view := ListView {
            for row[idx] in root.rows : TableViewRow {
                selected: idx == root.current-row;
                even: mod(idx, 2) == 0;

                pointer-event(pe, pos) => {
                    root.row-pointer-event(idx, pe, {
                        x: pos.x - root.absolute-position.x,
                        y: pos.y - root.absolute-position.y,
                    });
                }

                clicked => {
                    root.focus();
                    root.set-current-row(idx);
                }

                for cell[index] in row : TableViewCell {
                    private property <bool> has_inner_focus;

                    horizontal-stretch: root.columns[index].horizontal-stretch;
                    min-width: max(columns[index].min-width, columns[index].width);
                    preferred-width: self.min-width;
                    max-width: (index < columns.length && columns[index].width >= 1px) ? max(columns[index].min-width, columns[index].width) : 100000px;

                    Rectangle {
                        cell-text := Text {
                            width: 100%;
                            height: 100%;
                            overflow: elide;
                            vertical-alignment: center;
                            text: cell.text;
                            font-weight: FHFontSettings.body.font-weight;
                            font-size: FHFontSettings.body.font-size;
                            color: mod(idx, 2) == 0 ? FHPalette.foreground.darker(0.15) : FHPalette.foreground;
                        }
                    }
                }
            }
        }
    }

    focus-scope := FocusScope {
        x: 0;
        width: 0; // Do not react on clicks

        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                root.set-current-row(root.current-row - 1);
                return accept;
            } else if (event.text == Key.DownArrow) {
                root.set-current-row(root.current-row + 1);
                return accept;
            }
            reject
        }
    }
}
